[package]
name = "build-planet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
env_logger = "0.11.2"
log = "0.4.21"
tokio = { version = "1.36.0", features = ["full"] }
