name: Push `dev` containers

on:
  push:
    branches: [dev]

jobs:
  build:
    name: Push dev images to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          # pinning to `latest` requires using the GH API, which causes spurious rate limiting errors
          version: "0.7.4"
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u headwaymaps --password-stdin
      - name: Earthly version check
        run: earthly --version
      - name: Push dev images
        run: earthly --push +images --tags=dev
      - name: Push dev branded images
        run: earthly --push +images --branding=maps.earth --tags "maps-earth-dev"
